name = "jwt-do"
route = { pattern = "*/*", zone_name = "jwt.do" }
main = "worker.js"
usage_model = "unbound"
compatibility_date = "2022-09-23"

services = [
  { binding = "APIKEYS", service = "apikeys-do", environment = "production" }
]
