name = "jwt-do"
route = { pattern = "*/*", zone_name = "jwt.do" }
main = "worker.js"
usage_model = "unbound"
compatibility_date = "2022-09-23"

tail_consumers = [{service = "tail", environment = "production"}]

services = [
  { binding = "APIKEYS", service = "apikeys-do", environment = "production" }
]

[vars]
ADMIN_IDS = "112662125,4130910,83304860,837697,87502003"
